#
# external aliases
alias wp='docker run -it --rm --volumes-from objWp --network container:objWp wordpress:cli'
alias wpconf='wp config'
alias wpd='wp db'
alias wph='wp help'
alias wpi='wp --info'
alias wpp='wp plugin'
alias wppa='wp plugin activate'
alias wppd='wp plugin deactivate'
alias wppi='wp plugin install'
alias wppia='wp plugin install --activate'
alias wpps='wp plugin search'
alias wppsa='wp plugin search --format=csv --fields=name,slug,version,requires,tested,rating,ratings,num_ratings,downloaded,active_installs,added,last_updated,short_description,tags,homepage'
alias wppsd='wp plugin search --fields=name,short_description,author,tested,homepage'
alias wppsr='wp plugin search --fields=name,rating,ratings,num_ratings,downloaded,last_updated,active_installs'
alias wppu='wp plugin uninstall'
alias wppud='wp plugin uninstall --deactivate'
alias wpu='wp user'
